CREATE TABLE CONSTELACIONES(
GENITIVO VARCHAR2 (20) NOT NULL,
ABREVIATURA VARCHAR2 (10) NOT NULL,
LATITUDES VARCHAR2 (20),
MES_MEJOR_VIS VARCHAR2 (20),
NOMBRE_POPULAR VARCHAR2(60),
HEMISFERIO VARCHAR2(10),
COMENTARIOS VARCHAR2(100),
CONSTRAINT PK_CONSTELACIONES PRIMARY KEY (GENITIVO),
CONSTRAINT UK_CONSTELACIONES UNIQUE (ABREVIATURA)
);

CREATE TABLE FRONTERA(
GENITIVO_CONST VARCHAR2 (20) NOT NULL,
GENITIVO_CONST_FR VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_FRONTERA PRIMARY KEY (GENITIVO_CONST, GENITIVO_CONST_FR),
CONSTRAINT FK_CONSTELACION FOREIGN KEY (GENITIVO_CONST) REFERENCES CONSTELACIONES (GENITIVO),
CONSTRAINT FK_CONSTELACION_FRONTERA FOREIGN KEY (GENITIVO_CONST_FR) REFERENCES CONSTELACIONES (GENITIVO)
);

CREATE TABLE UBICACION(
POBLACION VARCHAR2 (60) NOT NULL,
PROVINCIA VARCHAR2 (60),
PAIS VARCHAR2(40),
HEMISFERIO VARCHAR2 (10),
CONSTRAINT PK_UBICACION PRIMARY KEY (POBLACION)
);

CREATE TABLE OBSERVACION(
POBLACION_UBI VARCHAR2 (60) NOT NULL,
GENITIVO_CONST_UBI VARCHAR2 (20) NOT NULL,
FECHA DATE NOT NULL,
CONSTRAINT PK_OBSERVACION PRIMARY KEY (POBLACION_UBI, GENITIVO_CONST_UBI, FECHA),
CONSTRAINT FK_OBSERV_UBICACION FOREIGN KEY (POBLACION_UBI) REFERENCES UBICACION (POBLACION),
CONSTRAINT FK_OBSERV_CONSTELACION FOREIGN KEY (GENITIVO_CONST_UBI) REFERENCES CONSTELACIONES (GENITIVO)
);


CREATE TABLE COMETA (
NOMBRE_COMETA VARCHAR2 (50)NOT NULL,
FECHA_DESC DATE,
DESCUBRIDOR VARCHAR2(100),
CONSTRAINT PK_COMETA PRIMARY KEY (NOMBRE_COMETA)
);

CREATE TABLE LLUVIA_ESTRELLAS(
NOMBRE_LLUVIA VARCHAR2(50) NOT NULL,
NOM_COMETA VARCHAR2 (50) NOT NULL,
GENITIVO_CONST_LLUVIA VARCHAR (20) NOT NULL,
INICIO VARCHAR2 (8),
FIN VARCHAR2 (8),
RADIANTE VARCHAR2 (8),
METEOROS_HORA NUMBER,
CONSTRAINT PK_LLUVIA PRIMARY KEY (NOMBRE_LLUVIA),
CONSTRAINT FK_LLUVIA_CONSTELACION FOREIGN KEY (GENITIVO_CONST_LLUVIA) REFERENCES CONSTELACIONES (GENITIVO),
CONSTRAINT FK_LLUVIA_COMETA FOREIGN KEY (NOM_COMETA) REFERENCES COMETA (NOMBRE_COMETA)
);


CREATE TABLE ESTRELLAS(
LETRA VARCHAR2(20) NOT NULL,
GENITIVO_CONST_EST VARCHAR2 (20) NOT NULL,
NOM_ESTRELLA VARCHAR2 (50),
TIPO VARCHAR2 (25),
MAGNITUD NUMBER,
DISTANCIA_AÑOSLUZ NUMBER,
NOMBRE_ASTERISMO VARCHAR2 (50),
NUM_CAT_NEBULOSA VARCHAR2(15),
NUM_CAT_CUMULO VARCHAR2 (15),
CONSTRAINT PK_ESTRELLAS PRIMARY KEY (LETRA, GENITIVO_CONST_EST),
CONSTRAINT FK_ESTRELLAS_CONST FOREIGN KEY (GENITIVO_CONST_EST) REFERENCES CONSTELACIONES (GENITIVO)
);


CREATE TABLE AGRUPACION(
LETRA_EST VARCHAR2(20) NOT NULL,
GENITIVO_CONST_EST VARCHAR2(20) NOT NULL,
LETRA_EST_AGR VARCHAR2(20) NOT NULL,
GENITIVO_CONST_EST_AGR VARCHAR2(20) NOT NULL,
CONSTRAINT PK_AGRUPACION PRIMARY KEY (LETRA_EST,GENITIVO_CONST_EST,LETRA_EST_AGR,GENITIVO_CONST_EST_AGR),
CONSTRAINT FK_ESTRELLA FOREIGN KEY (LETRA_EST,GENITIVO_CONST_EST)REFERENCES ESTRELLAS (LETRA, GENITIVO_CONST_EST),
CONSTRAINT FK_ESTRELLA_AGRUP FOREIGN KEY (LETRA_EST_AGR,GENITIVO_CONST_EST_AGR) REFERENCES ESTRELLAS (LETRA, GENITIVO_CONST_EST)
);

CREATE TABLE ASTERISMOS(
NOM_ASTERISMO VARCHAR2(100) NOT NULL,
VISIBILIDAD VARCHAR2 (50),
HEMISFERIO VARCHAR2 (10),
CONSTRAINT PK_ASTERISMO PRIMARY KEY (NOM_ASTERISMO)
);

ALTER TABLE ESTRELLAS ADD CONSTRAINT FK_ESTRELLA_ASTERISMO FOREIGN KEY (NOMBRE_ASTERISMO) REFERENCES ASTERISMOS (NOM_ASTERISMO);

CREATE TABLE PLANETARIA(
LETRA_EST_PL VARCHAR2(20) NOT NULL,
GENITIVO_CONST_PL VARCHAR2 (20) NOT NULL,
SISTEMA VARCHAR2 (50),
CONSTRAINT PK_PLANETARIA PRIMARY KEY (LETRA_EST_PL, GENITIVO_CONST_PL),
CONSTRAINT FK_PLANETARIA_ESTRELLA FOREIGN KEY (LETRA_EST_PL, GENITIVO_CONST_PL) REFERENCES ESTRELLAS (LETRA, GENITIVO_CONST_EST)
);

CREATE TABLE PLANETA(
NOM_PLANETA VARCHAR2 (20) NOT NULL,
TIPO VARCHAR2 (30),
ZONA_HABITABLE VARCHAR2 (2),
DIAMETRO_KM NUMBER,
LETRA_EST_PL VARCHAR2 (20) NOT NULL,
GENITIVO_EST_PL VARCHAR2 (20) NOT NULL,
DIST_EST_MILLONES_KM NUMBER,
CONSTRAINT PK_PLANETA PRIMARY KEY (NOM_PLANETA),
CONSTRAINT FK_PLANETA_ESTRELLA FOREIGN KEY (LETRA_EST_PL, GENITIVO_EST_PL) REFERENCES ESTRELLAS (LETRA, GENITIVO_CONST_EST)
);


CREATE TABLE SATELITE(
NOM_SATELITE VARCHAR2 (50) NOT NULL,
DIAMETRO_KM NUMBER,
NOM_PLANETA_S VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_SATELITE PRIMARY KEY (NOM_SATELITE),
CONSTRAINT FK_SATELITE_PLANETA FOREIGN KEY (NOM_PLANETA_S) REFERENCES PLANETA (NOM_PLANETA)
);


CREATE TABLE OBJETOS (
NUM_CATALOGO VARCHAR2 (15) NOT NULL,
NOM_OBJETO VARCHAR2 (30),
MAGNITUD NUMBER,
DISTANCIA_AÑOSLUZ NUMBER,
GENITIVO_CONST_OBJ VARCHAR2 (20) NOT NULL,
CONSTRAINT PK_OBJETOS PRIMARY KEY (NUM_CATALOGO),
CONSTRAINT FK_OBJETO_CONSTELACION FOREIGN KEY (GENITIVO_CONST_OBJ) REFERENCES CONSTELACIONES (GENITIVO)
);

CREATE TABLE NEBULOSA (
NUM_CATALOGO_NEBULOSA VARCHAR2 (15) NOT NULL,
TIPO VARCHAR2 (30),
CONSTRAINT PK_NEBULOSA PRIMARY KEY (NUM_CATALOGO_NEBULOSA),
CONSTRAINT FK_NEBULOSA_OBJETO FOREIGN KEY (NUM_CATALOGO_NEBULOSA) REFERENCES OBJETOS (NUM_CATALOGO)
);

ALTER TABLE ESTRELLAS ADD CONSTRAINT FK_ESTRELLAS_NEBULOSA FOREIGN KEY (NUM_CAT_NEBULOSA) REFERENCES NEBULOSA (NUM_CATALOGO_NEBULOSA);

CREATE TABLE GALAXIA (
NUM_CATALOGO_GALAXIA VARCHAR2 (15) NOT NULL,
TIPO VARCHAR2 (30),
CONSTRAINT PK_GALAXIA PRIMARY KEY (NUM_CATALOGO_GALAXIA),
CONSTRAINT FK_GALAXIA_OBJETO FOREIGN KEY (NUM_CATALOGO_GALAXIA) REFERENCES OBJETOS (NUM_CATALOGO)
);

CREATE TABLE CUMULO (
NUM_CATALOGO_CUMULO VARCHAR2 (15) NOT NULL,
NUM_ESTRELLAS NUMBER,
TIPO VARCHAR2(15),
CONSTRAINT PK_CUMULO PRIMARY KEY (NUM_CATALOGO_CUMULO),
CONSTRAINT FK_CUMULO_OBJETO FOREIGN KEY (NUM_CATALOGO_CUMULO) REFERENCES OBJETOS (NUM_CATALOGO)
);

ALTER TABLE ESTRELLAS ADD CONSTRAINT FK_ESTRELLAS_CUMULOS FOREIGN KEY (NUM_CAT_CUMULO)REFERENCES CUMULO(NUM_CATALOGO_CUMULO);

CREATE TABLE IMAGEN(
NUM_IMAGEN NUMBER NOT NULL,
TIPO VARCHAR2 (20),
ESPECIFICACIONES VARCHAR2 (200),
GENITIVO_CONST_IM VARCHAR2(20),
POBLACION_IM VARCHAR2 (60),
FECHA_IM DATE,
HORA VARCHAR2 (10),
CONSTRAINT PK_IMAGEN PRIMARY KEY (NUM_IMAGEN),
CONSTRAINT FK_IMAGEN_OBSERV FOREIGN KEY (GENITIVO_CONST_IM, POBLACION_IM, FECHA_IM) REFERENCES OBSERVACION (GENITIVO_CONST_UBI, POBLACION_UBI, FECHA)
);

CREATE TABLE CATALOGAR (
GENITIVO_CAT VARCHAR2 (20) NOT NULL,
NUM_IMAGEN_CAT NUMBER NOT NULL,
ESTADO VARCHAR2(50),
CONSTRAINT PK_CATALOGAR PRIMARY KEY (GENITIVO_CAT, NUM_IMAGEN_CAT),
CONSTRAINT FK_CAT_IMAGEN FOREIGN KEY (NUM_IMAGEN_CAT) REFERENCES IMAGEN (NUM_IMAGEN),
CONSTRAINT FK_CAT_CONSTE FOREIGN KEY (GENITIVO_CAT) REFERENCES CONSTELACIONES (GENITIVO)
);

CREATE TABLE REPRESENTAR (
NUM_OBJETO_REP VARCHAR2(15) NOT NULL,
NUM_IMAGEN_REP NUMBER NOT NULL,
DESCRIPCION VARCHAR2(200),
CONSTRAINT PK_REPRESENTAR PRIMARY KEY (NUM_OBJETO_REP, NUM_IMAGEN_REP),
CONSTRAINT FK_REPRES_OBJETO FOREIGN KEY (NUM_OBJETO_REP) REFERENCES OBJETOS (NUM_CATALOGO),
CONSTRAINT FK_REPRES_IMAGEN FOREIGN KEY (NUM_IMAGEN_REP) REFERENCES IMAGEN (NUM_IMAGEN)
);

CREATE TABLE CONJUNCION (
NOM_PLANETA_1 VARCHAR2 (20) NOT NULL,
NOM_PLANETA_2 VARCHAR2 (20) NOT NULL,
POBLACION_CONJ VARCHAR2 (60) NOT NULL,
GENITIVO_CONST_CONJ VARCHAR2 (20) NOT NULL,
FECHA_CONJ DATE NOT NULL,
HORA VARCHAR2(10),
CONSTRAINT PK_CONJUNCION PRIMARY KEY (NOM_PLANETA_1,POBLACION_CONJ,GENITIVO_CONST_CONJ,FECHA_CONJ),
CONSTRAINT UK_CONJUNCION UNIQUE (NOM_PLANETA_2,POBLACION_CONJ,GENITIVO_CONST_CONJ,FECHA_CONJ),
CONSTRAINT FK_CONJUNCION_PLANETA_1 FOREIGN KEY (NOM_PLANETA_1) REFERENCES PLANETA (NOM_PLANETA),
CONSTRAINT FK_CONJUNCION_PLANETA_2 FOREIGN KEY (NOM_PLANETA_2) REFERENCES PLANETA (NOM_PLANETA),
CONSTRAINT FK_CONJUNCION_OBSERVACION FOREIGN KEY (POBLACION_CONJ, GENITIVO_CONST_CONJ, FECHA_CONJ) REFERENCES OBSERVACION (POBLACION_UBI, GENITIVO_CONST_UBI, FECHA)
);





