-- A. Consultas simples de una sola tabla.

    -- 1. IMAGENES SACADAS EN EL AÑO 2014 , A 3200-ISO Y EN LUGARES CUYOS NOMBRES SEAN COMPUESTOS
    SELECT * FROM IMAGEN 
    WHERE TO_CHAR(FECHA_IM,'YYYY')='2014' AND ESPECIFICACIONES LIKE '%3200-ISO%'
    AND INSTR(POBLACION_IM, ' ')>0;
    
    -- 2. SABIENDO QUE ALICANTE ESTA A LATITUD +38º GRADOS
    -- QUE CONSTELACIONES SE VEN MEJOR ESTE MES. COMENTAR CUALES DE ELLAS SON AUSTRALES Y CUALES BOREALES
    
    SELECT NOMBRE_POPULAR ||' --> ' || DECODE (HEMISFERIO, 'NORTE', 'BOREAL', 'AUSTRAL') FROM CONSTELACIONES WHERE
    (SUBSTR(LATITUDES,0,3))>'+38' AND MES_MEJOR_VIS = RTRIM(TO_CHAR(SYSDATE, 'MONTH'));
    
    -- 3. lUVIAS DE ESTRELLAS QUE PODEMOS VER DESDE HOY HASTA AGOSTO Y CUANDO EMPIEZAN
    
     SELECT NOMBRE_LLUVIA, INICIO FROM LLUVIA_ESTRELLAS
     WHERE TO_DATE(INICIO,'DD/MM')> SYSDATE AND TO_DATE(INICIO,'DD/MM')BETWEEN SYSDATE AND '30/08/2017';
     
    -- 4. DISTANCIA EN MILLONES DE KM DE JUPITER HASTA MARTE
    
    SELECT (PL1.DIST_EST_MILLONES_KM - PL2.DIST_EST_MILLONES_KM) DISTANCIA_MILL_KM FROM PLANETA PL1, PLANETA PL2 
    WHERE PL1.NOM_PLANETA='JUPITER' AND PL2.NOM_PLANETA='MARTE';
    
    -- 5. OBJETOS DEL CATALOGO MESSIER O DEL NUEVO CATALOGO GENERAL QUE SEAN VISIBLES A SIMPLE VISTA 
    
    SELECT NOM_OBJETO FROM OBJETOS WHERE (NUM_CATALOGO LIKE 'M%' OR NUM_CATALOGO LIKE 'NGC%') AND MAGNITUD<6;
    

-- B y H, Actualizaciones: Normales y  con subconsultas y where. Y borrados.

    -- 1.ACTUALIZAR A 'ECLIPTICA' LOS COMENTARIOS DE LAS CONSTELACIONES ZOODIACALES.
    
    UPDATE CONSTELACIONES SET COMENTARIOS='ECLIPTICA' 
    WHERE NOMBRE_POPULAR =ANY
    ('ARIES','TAURO','GEMINIS','CANCER','LEO','VIRGO','LIBRA','ESCORPIO', 'SAGITARIO', 'CAPRICORNIO','ACUARIO','PISCIS');
    
    -- 2. ANADIR COLUMNA ORBITA_AÑOS A LA TABLA COMETA Y ACTUALIZAR
    ALTER TABLE COMETA ADD ORBITA_AÑOS NUMBER;
    UPDATE COMETA SET ORBITA_AÑOS= DECODE(NOMBRE_COMETA, 'SWIFT TUTTLE', 133,
                                                         'FAETON', 3,
                                                         'GIACOBINI-ZINNER', 6,
                                                         'HALLEY', 75,
                                                         'TEMPLE TUTTLE',33,
                                                         NULL);
                                                         
    -- 3. RENOMBRAR LA COLUMNA TIPO DE LA TABLA ESTRELLAS A EVOLUCION Y
    -- CAMBIAR EL TIPO BLANCA Y BLANCO/AZUL POR SECUENCIA PRINCIPAL Y EL QUE ESTE A NULL A 'DESCONOCIDA'
    
    ALTER TABLE ESTRELLAS RENAME COLUMN TIPO TO EVOLUCION;
    UPDATE ESTRELLAS SET EVOLUCION = DECODE (EVOLUCION, 'BLANCA', 'SECUENCIA PRINCIPAL',
                                                        'BLANCA/AZUL', 'SECUENCIA PRINCIPAL',
                                                        NULL, 'DESCONOCIDA')
    WHERE EVOLUCION IN ('BLANCA','BLANCA/AZUL') OR EVOLUCION IS NULL;
    
    --  4.ACTUALIZAR CAMPO NOMBRE_NEBULOSA DE ETA CARINAE
    UPDATE ESTRELLAS SET NUM_CAT_NEBULOSA=(SELECT NUM_CATALOGO FROM OBJETOS 
                                           WHERE NOM_OBJETO= 'NEBULOSA DE LA QUILLA')
    WHERE NOM_ESTRELLA='ETA CARINAE';
                                                
    -- 5. AÑADIR UN CAMPO NOMBRE_ALTERNATIVO A ESTRELLAS , QUE CONTENGA SU LETRA Y LA ABREVIATURA DE SU CONSTELACION
    -- SOLO LAS QUE SEAN DE DESIGNACION ALFA, BETA O GAMMA O LAS QUE SEAN PLANETARIAS
    
    ALTER TABLE ESTRELLAS ADD NOMBRE_ALT VARCHAR2(20);
    
    UPDATE ESTRELLAS SET NOMBRE_ALT= (LETRA||' - '||(SELECT ABREVIATURA 
                                                     FROM CONSTELACIONES WHERE GENITIVO=GENITIVO_CONST_EST))
    WHERE LETRA =ANY ('ALFA', 'BETA', 'GAMMA') 
    OR GENITIVO_CONST_EST IN (SELECT GENITIVO_CONST_PL FROM PLANETARIA);

                                                            
    -- 6. Y BORRARLO PORQUE EN REALIDAD NO LO QUIERO.
    ALTER TABLE ESTRELLAS DROP COLUMN NOMBRE_ALT;
        

-- C. Consultas con mas de una tabla (un outer join)

    -- 1. NOMBRES DE CONSTELACIONES QUE CONTENGAN OBJETOS A MAS DE 20000 AÑOS LUZ DE DISTANCIA
    -- Y ESTEN CATALOGADAS CON MAPA INCOMPLETO.
    
    SELECT NOMBRE_POPULAR FROM CONSTELACIONES, CATALOGAR, IMAGEN
    WHERE GENITIVO IN (SELECT GENITIVO_CONST_OBJ FROM OBJETOS WHERE DISTANCIA_AÑOSLUZ>2000)
    AND GENITIVO=GENITIVO_CAT AND NUM_IMAGEN_CAT=NUM_IMAGEN 
    AND TIPO='MAPA' AND ESTADO='INCOMPLETO';
    
    -- 2. CANTIDAD DE CUMULOS REPRESENTADOS EN IMAGENES 

    SELECT COUNT(*) FROM CUMULO WHERE NUM_CATALOGO_CUMULO IN 
    (SELECT NUM_CATALOGO FROM OBJETOS, IMAGEN, REPRESENTAR
    WHERE NUM_CATALOGO=NUM_OBJETO_REP 
    AND NUM_IMAGEN=NUM_IMAGEN_REP);
    
    -- 3. NOMBRE DE CONSTELACIONES OBERVADAS Y SUS FECHAS, Y LAS NO OBSERVADAS TAMBIEN.
    -- QUE UBIQUEN LLUVIAS DE ESTRELLAS, Y LAS QUE NO TAMBIEN.
    -- ORDENAR POR LLUVIA.
    
    SELECT NOMBRE_POPULAR, NOMBRE_LLUVIA, FECHA FROM CONSTELACIONES, OBSERVACION, LLUVIA_ESTRELLAS 
    WHERE GENITIVO=GENITIVO_CONST_UBI(+) AND GENITIVO=GENITIVO_CONST_LLUVIA(+)
    ORDER BY NOMBRE_LLUVIA;
    
-- D. Consultas usando funciones

    -- 1. TODOS LOS DATOS DE FOTOS SACADAS EL DIA DE MAXIMA ACTIVIDAD DE LAS GEMINIDAS
    
    SELECT * FROM IMAGEN 
    WHERE (FECHA_IM, GENITIVO_CONST_IM, POBLACION_IM) IN 
                                                        (SELECT FECHA, GENITIVO_CONST_UBI, POBLACION_UBI 
                                                        FROM OBSERVACION, CONSTELACIONES, UBICACION, LLUVIA_ESTRELLAS
                                                        WHERE POBLACION_UBI=POBLACION 
                                                        AND GENITIVO_CONST_UBI=GENITIVO 
                                                        AND GENITIVO=GENITIVO_CONST_LLUVIA 
                                                        AND TO_CHAR(FECHA,'DD')=SUBSTR(RADIANTE,1,2) 
                                                        AND TO_CHAR(FECHA,'MM')=SUBSTR(RADIANTE,4)
                                                        AND NOMBRE_LLUVIA='GEMINIDAS');
    
    -- 2. LOS 3 ULTIMOS CARACTERES DEL NOMBRE DE LA ESTRELLA PLANETARIA MAS LEJANA.
    
    SELECT SUBSTR(NOM_ESTRELLA,-3) FROM ESTRELLAS, PLANETARIA
    WHERE GENITIVO_CONST_EST=GENITIVO_CONST_PL AND LETRA=LETRA_EST_PL
    AND DISTANCIA_AÑOSLUZ=(SELECT MAX(DISTANCIA_AÑOSLUZ)FROM ESTRELLAS, PLANETARIA
                           WHERE GENITIVO_CONST_EST=GENITIVO_CONST_PL AND LETRA=LETRA_EST_PL);
                           
    -- 3. CANTIDAD DE ESTRELLAS ENTRE GIGANTES Y SUPERGIGANTES,
    -- EL CARACTER ASCII DEL NUMERO RESULTADO MULTIPLICADO POR 10
    -- LA MEDIA DE SUS DISTANCIAS RESPECTO A NOSOTROS Y LA SUMA DE SUS MAGNITUDES
    
    SELECT COUNT(*)|| ' x 10',CHR(COUNT(*)*10), SUM(MAGNITUD), AVG(DISTANCIA_AÑOSLUZ)
    FROM ESTRELLAS WHERE INSTR(EVOLUCION,'GIGANTE')>0;
    
-- E. Consultas usando Group By.

    -- 1. CUANTAS NEBULOSAS HAY EN CONSTELACIONES DE LA ECLIPTICA
    
    SELECT COUNT(*) 
    FROM CONSTELACIONES, OBJETOS, NEBULOSA 
    WHERE NUM_CATALOGO=NUM_CATALOGO_NEBULOSA 
    AND GENITIVO=GENITIVO_CONST_OBJ
    AND COMENTARIOS='ECLIPTICA'
    GROUP BY COMENTARIOS;
    
    --2. ULTIMA FECHA EN LA QUE SE HIZO UNA FOTO EN CADA HEMISFERIO
    
    SELECT HEMISFERIO, MAX(FECHA) FROM OBSERVACION, UBICACION
    WHERE POBLACION=POBLACION_UBI
    GROUP BY HEMISFERIO;
    
    -- 3. CANTIDAD DE SATELITES EN CADA PLANETA CUYO DIAMETRO SEA MAYOR AL DEL PLANETA PLUTON
    
    SELECT NOM_PLANETA_S, COUNT(*) FROM SATELITE SA, PLANETA PL
    WHERE SA.DIAMETRO_KM > PL.DIAMETRO_KM AND NOM_PLANETA='PLUTON'
    GROUP BY NOM_PLANETA_S;
    
-- F. Consultas usando subconsultas

    -- 1. NEBULOSAS DE EMISION QUE NO ESTEN REPRESENTADAS EN IMAGENES
    -- PERO LA CONSTELACION DONDE SE UBICAN SI ESTEN CATALOGADAS
    -- Y GALAXIAS LENTICULARES DE CONSTELACIONES NO CATALOGADAS.
    
    SELECT NOM_OBJETO FROM OBJETOS
    WHERE NUM_CATALOGO IN (SELECT NUM_CATALOGO_NEBULOSA FROM NEBULOSA WHERE TIPO LIKE '%EMISION%')
    AND NUM_CATALOGO NOT IN (SELECT NUM_OBJETO_REP FROM REPRESENTAR WHERE NUM_OBJETO_REP=NUM_CATALOGO)
    AND GENITIVO_CONST_OBJ IN (SELECT GENITIVO FROM CONSTELACIONES, CATALOGAR WHERE GENITIVO=GENITIVO_CAT)
    UNION
    SELECT NOM_OBJETO FROM OBJETOS 
    WHERE NUM_CATALOGO IN (SELECT NUM_CATALOGO_GALAXIA FROM GALAXIA WHERE TIPO LIKE'%LENTICULAR%')
    AND GENITIVO_CONST_OBJ NOT IN (SELECT GENITIVO FROM CONSTELACIONES, CATALOGAR WHERE GENITIVO=GENITIVO_CAT);
     
    -- 2. NOMBRE DE CONSTELACIONES QUE CONTENGAN GALAXIAS (LA IDENTIFICACION DE ESTAS) Y QUE 
    --HAGAN FRONTERA CON ANDROMEDA EN EL HEMISFERIO NORTE 

    SELECT DOS.NOMBRE_POPULAR, SUB.NUM_CATALOGO FROM CONSTELACIONES UNO, CONSTELACIONES DOS, FRONTERA,
    (SELECT NUM_CATALOGO, GENITIVO_CONST_OBJ FROM OBJETOS, GALAXIA  WHERE NUM_CATALOGO=NUM_CATALOGO_GALAXIA) SUB  
    WHERE UNO.GENITIVO=GENITIVO_CONST 
    AND DOS.GENITIVO=GENITIVO_CONST_FR  
    AND SUB.GENITIVO_CONST_OBJ=GENITIVO_CONST_FR
    AND UNO.NOMBRE_POPULAR='ANDROMEDA' AND DOS.HEMISFERIO ='NORTE';

-- G. Consultas usando subconsultas y group by con having

    -- 1 . PLANETAS CON MAS DE DOS SATELITES QUE HAYAN PARTICIPADO EN MAS DE UNA CONJUNCION.
    --EL SISTEMA DEL QUE FORMAN PARTE Y EL NOMBRE DE SU ESTRELLA.

    SELECT NOM_PLANETA, SISTEMA, NOM_ESTRELLA FROM PLANETA PL, PLANETARIA PL2, ESTRELLAS
    WHERE NOM_PLANETA IN
                        (SELECT NOM_PLANETA FROM PLANETA, CONJUNCION
                         WHERE NOM_PLANETA IN 
                                             (SELECT NOM_PLANETA_S FROM SATELITE GROUP BY NOM_PLANETA_S HAVING COUNT(*)>2)
                         AND NOM_PLANETA=NOM_PLANETA_1 OR NOM_PLANETA=NOM_PLANETA_2
                         GROUP BY NOM_PLANETA HAVING COUNT(*)>1)
    AND PL.LETRA_EST_PL=PL2.LETRA_EST_PL AND PL.GENITIVO_EST_PL=GENITIVO_CONST_PL
    AND PL2.LETRA_EST_PL=LETRA AND GENITIVO_CONST_PL=GENITIVO_CONST_EST;
    
   
   -- 2. NOMBRE DE LA CONSTELACION CON MAYOR NUMERO DE SISTEMAS ESTELARES MULTIPLES.
  
   SELECT DISTINCT NOMBRE_POPULAR FROM CONSTELACIONES, ESTRELLAS 
   WHERE GENITIVO=GENITIVO_CONST_EST
   AND (LETRA, GENITIVO_CONST_EST) IN (SELECT LETRA, ES.GENITIVO_CONST_EST 
                                       FROM ESTRELLAS ES,  AGRUPACION AG
                                       WHERE LETRA=LETRA_EST AND ES.GENITIVO_CONST_EST=AG.GENITIVO_CONST_EST 
                                       GROUP BY LETRA, ES.GENITIVO_CONST_EST
                                       HAVING COUNT(*)= (SELECT MAX(COUNT(*))FROM AGRUPACION 
                                                        GROUP BY LETRA_EST, GENITIVO_CONST_EST));
    
-- I. Consultas usando operadores de conjuntos.

    -- 1. CONSTELACION CON MAYOR NUMERO DE ESTRELLAS Y LA QUE MENOS TIENE, CONTANDO SOLO LAS QUE TENGAN NOMBRES 
    -- ELEGIR DE CADA UNA LA MENOR ALFABETICAMENTE 
    
    SELECT MIN(NOMBRE_POPULAR) FROM CONSTELACIONES 
    WHERE NOMBRE_POPULAR IS NOT NULL 
    AND GENITIVO IN(
    SELECT GENITIVO_CONST_EST FROM ESTRELLAS GROUP BY GENITIVO_CONST_EST
    HAVING COUNT(*)= (SELECT MAX(COUNT(*)) FROM ESTRELLAS GROUP BY GENITIVO_CONST_EST))
    UNION
    SELECT MIN(NOMBRE_POPULAR) FROM CONSTELACIONES 
    WHERE NOMBRE_POPULAR IS NOT NULL AND 
    GENITIVO IN(
    SELECT GENITIVO_CONST_EST FROM ESTRELLAS GROUP BY GENITIVO_CONST_EST
    HAVING COUNT(*)= (SELECT MIN(COUNT(*)) FROM ESTRELLAS GROUP BY GENITIVO_CONST_EST));
    
    -- 2. ESTRELLAS QUE TENGAN NOMBRE Y SEAN VISIBLES A SIMPLE VISTA
    -- O ESTRELLAS QUE SEAN SUPERGIGANTES ROJAS Y LAS MAS LUMINOSAS DE SU CONSTELACION
    -- Y ESTRELLAS DE CONSTELACIONES CATALOGADAS CON MAPAS COMPLETOS QUE TENGAN MAS DE 1 SISTEMA ESTELAR

    SELECT * FROM ESTRELLAS WHERE NOM_ESTRELLA IS NOT NULL AND MAGNITUD<6
    OR EVOLUCION='SUPERGIGANTE ROJA' AND LETRA='ALFA'
    UNION
    SELECT * FROM ESTRELLAS WHERE GENITIVO_CONST_EST IN
        (SELECT GENITIVO FROM CONSTELACIONES, CATALOGAR, IMAGEN
        WHERE GENITIVO=GENITIVO_CAT AND NUM_IMAGEN=NUM_IMAGEN_CAT AND ESTADO='COMPLETO')
    AND GENITIVO_CONST_EST IN 
        (SELECT GENITIVO_CONST_EST FROM AGRUPACION GROUP BY GENITIVO_CONST_EST HAVING COUNT(*)>1);
        
-- J. Vistas normales y materializada.

    -- 1. Vista con el nombre y constelacion de las estrellas de designacion beta (solo las que tengan nombre) y
    -- visibles a simple vista.
    
    CREATE OR REPLACE VIEW EST_B_VISIBLES ( NOMBRE, CONSTELACION) AS
    SELECT NOM_ESTRELLA, NOMBRE_POPULAR
    FROM ESTRELLAS, CONSTELACIONES
    WHERE NOM_ESTRELLA IS NOT NULL AND MAGNITUD<=6 AND LETRA='BETA'
    AND GENITIVO=GENITIVO_CONST_EST;
    
    -- 2. VISTA CON TODAS LAS IMAGENES OBTENIDAS DEL AÑO 2015 , QUE MANTENGA ESTA RESTRICCION AL ACTUALIZAR
    
    CREATE OR REPLACE VIEW IMAGENES_2015 AS SELECT * FROM IMAGEN WHERE TO_CHAR(FECHA_IM,'YYYY')='2015'
    WITH CHECK OPTION;
    
    -- 3. VISTA MATERIALIZADA DE OBJETOS DE CIELO PROFUNDO UBICADOS EN EL HEMISFERIO NORTE.
    
    CREATE OR MATERIALIZED VIEW OBJETOS_NORTE 
    BUILD IMMEDIATE REFRESH ON COMMIT
    AS SELECT OB.* FROM OBJETOS OB, CONSTELACIONES 
    WHERE GENITIVO=OB.GENITIVO_CONST_OBJ
    AND HEMISFERIO='NORTE';

    
    
    

    






