CREATE OR REPLACE PACKAGE UNIVERSO.ESTADISTICAS IS
PROCEDURE INFO_MES (MES IN VARCHAR2, HEMIS IN VARCHAR2);
FUNCTION VISIBILIDAD (TIPO IN VARCHAR2, NOM IN VARCHAR2) RETURN VARCHAR2;
PROCEDURE RESULTADO_IMAGENES (NUM IN NUMBER);
PROCEDURE BUSCAR_ESTRELLAS (LET IN VARCHAR2,GEN IN VARCHAR2,NOM IN VARCHAR2);
END ESTADISTICAS; 
/

