CREATE OR REPLACE PACKAGE UNIVERSO.GESTION_UBICACIONES IS
PROCEDURE INSERTAR_UBICACION(POB IN VARCHAR2, PROV IN VARCHAR2, PAIS IN VARCHAR2, HEM IN VARCHAR2);
PROCEDURE MODIFICAR_UBICACION (POB IN VARCHAR2, PROV IN VARCHAR2, PA IN VARCHAR2, HEM IN VARCHAR2);
PROCEDURE ELIMINAR_UBICACION (POB IN VARCHAR2);
PROCEDURE CONSULTAR_UBICACION (POB IN VARCHAR);
END GESTION_UBICACIONES; 
/

